// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGWkULdml38bQxy1_HuAhf0_c3JJ4cGdc',
    appId: '1:935787381560:web:f18ce0281b464b7905f7cd',
    messagingSenderId: '935787381560',
    projectId: 'despesas-eu-deborah',
    authDomain: 'despesas-eu-deborah.firebaseapp.com',
    storageBucket: 'despesas-eu-deborah.appspot.com',
    measurementId: 'G-6RTWF9F6PK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4PjtaW2Opt89KLN4xiW10cKeVO3RYVQA',
    appId: '1:935787381560:android:4a87cc4b76f4d96605f7cd',
    messagingSenderId: '935787381560',
    projectId: 'despesas-eu-deborah',
    storageBucket: 'despesas-eu-deborah.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHocBD2mxDCpQHTTYuM6tHI1nrnPSWkQ8',
    appId: '1:935787381560:ios:5833b5fd9da8654605f7cd',
    messagingSenderId: '935787381560',
    projectId: 'despesas-eu-deborah',
    storageBucket: 'despesas-eu-deborah.appspot.com',
    iosBundleId: 'com.example.despesas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHocBD2mxDCpQHTTYuM6tHI1nrnPSWkQ8',
    appId: '1:935787381560:ios:f8902e84c557d12d05f7cd',
    messagingSenderId: '935787381560',
    projectId: 'despesas-eu-deborah',
    storageBucket: 'despesas-eu-deborah.appspot.com',
    iosBundleId: 'com.example.despesas.RunnerTests',
  );
}
